Repository lunit-io/design-system, pull requests merged in 2023-02, with the labels that each got.

#82 [LDS-9] refactor custom chip component
  packages/design-system/src/components/Chip/Chip.styled.ts
  packages/design-system/src/components/Chip/Chip.tsx
  packages/design-system/src/components/Chip/Chip.types.ts
  packages/design-system/src/components/Chip/consts.ts
  packages/design-system/src/components/Chip/index.ts
  packages/design-system/src/stories/components/Chip/Chip.stories.tsx
Labels: enhancement

#81 [DS-7] / Add Button Component and Story
  packages/design-system/.storybook/preview.js
  packages/design-system/src/components/Button/Button.styled.ts
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/Button/Button.types.ts
  packages/design-system/src/components/Button/const.ts
  packages/design-system/src/components/Button/index.ts
  packages/design-system/src/components/Button/utils/getButtonPaddingBySizeAndKind.ts
  packages/design-system/src/components/Button/utils/getIconButtonPaddingBySizeAndKind.ts
  packages/design-system/src/components/ToggleButton/ToggleButton.styled.ts
  packages/design-system/src/components/ToggleButton/ToggleButton.tsx
  packages/design-system/src/components/ToggleButton/ToggleButton.types.ts
  packages/design-system/src/components/ToggleButton/index.ts
  packages/design-system/src/components/ToggleButtonGroup/index.tsx
  packages/design-system/src/foundation/Typography/index.ts
  packages/design-system/src/stories/components/Button/BasicButton.stories.tsx
  packages/design-system/src/stories/components/Button/Button.stories.tsx
  packages/design-system/src/stories/components/Button/IconButton.stories.tsx
  packages/design-system/src/stories/components/Button/Kind.stories.tsx
  packages/design-system/src/stories/components/ToggleButton/Basic.stories.tsx
  packages/design-system/src/stories/components/ToggleButton/Group.stories.tsx
  packages/design-system/src/stories/components/ToggleButton/ToggleButtonKind.stories.tsx
  packages/design-system/src/stories/components/ToggleButton/WithIcon.stories.tsx
Labels: documentation, enhancement

#86 [LDS-9] add Typography token & add conditional controls
  packages/design-system/src/components/Chip/Chip.styled.ts
  packages/design-system/src/stories/components/Chip/Chip.stories.tsx
Labels: documentation, enhancement

#87 [LDS-2]: add core color token palette
  packages/design-system/src/stories/foundation/colors/Token.stories.tsx
  packages/design-system/src/stories/foundation/colors/styled.ts
Labels: documentation

#89 fix(chip): remove not-working if controls
  packages/design-system/src/stories/components/Chip/Chip.stories.tsx
Labels: bug

#90 [LDS-2][LDS-9] add hover effect on chip
  packages/design-system/src/components/Chip/Chip.styled.ts
  packages/design-system/src/components/Chip/Chip.tsx
Labels: enhancement
